In [3]:
import numpy as np
arr = np.array([[1,2,3],[2,4,6],[8,8,8]])
arr.shape

(3, 3)

In [4]:
arr

array([[1, 2, 3],
       [2, 4, 6],
       [8, 8, 8]])

In [6]:
arr = np.zeros((2,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
arr = np.ones((2,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
arr = np.identity((3))
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
arr = np.random.randn(3,4)
arr

array([[ 0.91327128, -0.81562244, -0.16306623, -0.84051767],
       [ 0.24627528,  0.46284396, -0.78159484, -0.28335419],
       [-0.23751984, -0.3617509 ,  1.16437923,  0.09405332]])

In [17]:
import pandas as pd

In [18]:
city_data = pd.read_csv(filepath_or_buffer = 'simplemaps-worldcities-basic.csv')
city_data.head(n=10)

city      city_ascii        lat        lng       pop  \
0   Qal eh-ye Now       Qal eh-ye  34.983000  63.133300    2997.0   
1     Chaghcharan     Chaghcharan  34.516701  65.250001   15000.0   
2     Lashkar Gah     Lashkar Gah  31.582998  64.360000  201546.0   
3          Zaranj          Zaranj  31.112001  61.886998   49851.0   
4      Tarin Kowt      Tarin Kowt  32.633298  65.866699   10000.0   
5    Zareh Sharan    Zareh Sharan  32.850000  68.416705   13737.0   
6        Asadabad        Asadabad  34.866000  71.150005   48400.0   
7         Taloqan         Taloqan  36.729999  69.540004   64256.0   
8  Mahmud-E Eraqi  Mahmud-E Eraqi  35.016696  69.333301    7407.0   
9      Mehtar Lam      Mehtar Lam  34.650000  70.166701   17345.0   

       country iso2 iso3 province  
0  Afghanistan   AF  AFG  Badghis  
1  Afghanistan   AF  AFG     Ghor  
2  Afghanistan   AF  AFG  Hilmand  
3  Afghanistan   AF  AFG   Nimroz  
4  Afghanistan   AF  AFG  Uruzgan  
5  Afghanistan   AF  AFG  Paktika  
6  Afghanistan   AF  AFG    Kunar  
7  Afghanistan   AF  AFG   Takhar  
8  Afghanistan   AF  AFG   Kapisa  
9  Afghanistan   AF  AFG  Laghman

In [19]:
city_data.tail()

city   city_ascii        lat        lng        pop   country  \
7317       Mutare       Mutare -18.970019  32.650038   216785.0  Zimbabwe   
7318       Kadoma       Kadoma -18.330006  29.909947    56400.0  Zimbabwe   
7319  Chitungwiza  Chitungwiza -18.000001  31.100003   331071.0  Zimbabwe   
7320       Harare       Harare -17.817790  31.044709  1557406.5  Zimbabwe   
7321     Bulawayo     Bulawayo -20.169998  28.580002   697096.0  Zimbabwe   

     iso2 iso3          province  
7317   ZW  ZWE        Manicaland  
7318   ZW  ZWE  Mashonaland West  
7319   ZW  ZWE            Harare  
7320   ZW  ZWE            Harare  
7321   ZW  ZWE          Bulawayo

In [20]:
# slicing
series_es= city_data.lat
type(series_es)
series_es[1:10:2]

1    34.516701
3    31.112001
5    32.850000
7    36.729999
9    34.650000
Name: lat, dtype: float64

In [21]:
series_es[:7]

0    34.983000
1    34.516701
2    31.582998
3    31.112001
4    32.633298
5    32.850000
6    34.866000
Name: lat, dtype: float64

In [22]:
series_es[:-7315]

0    34.983000
1    34.516701
2    31.582998
3    31.112001
4    32.633298
5    32.850000
6    34.866000
Name: lat, dtype: float64

In [24]:
# select first 5 rows and 4columns
city_data.iloc[:5,:4]

city   city_ascii        lat        lng
0  Qal eh-ye Now    Qal eh-ye  34.983000  63.133300
1    Chaghcharan  Chaghcharan  34.516701  65.250001
2    Lashkar Gah  Lashkar Gah  31.582998  64.360000
3         Zaranj       Zaranj  31.112001  61.886998
4     Tarin Kowt   Tarin Kowt  32.633298  65.866699

In [25]:
# baseline prediction of disease progression for future patients
from sklearn import datasets

diabetes = datasets.load_diabetes()
y= diabetes.target
x= diabetes.data
x.shape

(442, 10)

In [26]:
x[:5]

array([[ 0.03807591,  0.05068012,  0.06169621,  0.02187235, -0.0442235 ,
        -0.03482076, -0.04340085, -0.00259226,  0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, -0.02632783, -0.00844872,
        -0.01916334,  0.07441156, -0.03949338, -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, -0.00567061, -0.04559945,
        -0.03419447, -0.03235593, -0.00259226,  0.00286377, -0.02593034],
       [-0.08906294, -0.04464164, -0.01159501, -0.03665645,  0.01219057,
         0.02499059, -0.03603757,  0.03430886,  0.02269202, -0.00936191],
       [ 0.00538306, -0.04464164, -0.03638469,  0.02187235,  0.00393485,
         0.01559614,  0.00814208, -0.00259226, -0.03199144, -0.04664087]])

In [30]:
feature_names = ['age', 'sex', 'bmi', 'bp'
                's1','s2','s3','s4','s5','s6']

In [31]:
from sklearn import datasets
from sklearn.linear_model import Lasso
import numpy as np
from sklearn import linear_model, datasets
from sklearn.model_selection import GridSearchCV

In [33]:
# seperate our data into test and train
diabetes = datasets.load_diabetes()
x_train = diabetes.data[:310]
y_train = diabetes.target[:310]

x_test = diabetes.data[310:]
y_text = diabetes.data[310:]


In [34]:
# define model lasso and alphas
lasso = Lasso(random_state=0)
alphas = np.logspace(-4, -0.5, 30)

In [36]:
# initialize an estimator
estimator = GridSearchCV(lasso, dict(alpha=alphas))
estimator.fit(x_train, y_train)

/home/grace/.local/lib/python3.5/site-packages/sklearn/model_selection/_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
/home/grace/.local/lib/python3.5/site-packages/sklearn/model_selection/_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv='warn', error_score='raise-deprecating',
       estimator=Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=0,
   selection='cyclic', tol=0.0001, warm_start=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'alpha': array([1.00000e-04, 1.32035e-04, 1.74333e-04, 2.30181e-04, 3.03920e-04,
       4.01281e-04, 5.29832e-04, 6.99564e-04, 9.23671e-04, 1.21957e-03,
       1.61026e-03, 2.12611e-03, 2.80722e-03, 3.70651e-03, 4.89390e-03,
       6.46167e-03, 8.53168e-03, 1.12648e-02, 1.48735e-02, 1.96383e-02,
       2.59294e-02, 3.42360e-02, 4.52035e-02, 5.96846e-02, 7.88046e-02,
       1.04050e-01, 1.37382e-01, 1.81393e-01, 2.39503e-01, 3.16228e-01])},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [39]:
estimator.best_score_


0.4654063759023531

In [40]:
estimator.best_estimator_

Lasso(alpha=0.02592943797404667, copy_X=True, fit_intercept=True,
   max_iter=1000, normalize=False, positive=False, precompute=False,
   random_state=0, selection='cyclic', tol=0.0001, warm_start=False)

In [41]:
estimator.predict(x_test)

array([203.42104984, 177.6595529 , 122.62188598, 212.81136958,
       173.61633075, 114.76145025, 202.36033584, 171.70767813,
       164.28694562, 191.29091477, 191.41279009, 288.2772433 ,
       296.47009002, 234.53378413, 210.61427168, 228.62812055,
       156.74489991, 225.08834492, 191.75874632, 102.81600989,
       172.373221  , 111.20843429, 290.22242876, 178.64605207,
        78.13722832,  86.35832297, 256.41378529, 165.99622543,
       121.29260976, 153.48718848, 163.09835143, 180.0932902 ,
       161.4330553 , 155.80211635, 143.70181085, 126.13753819,
       181.06471818, 105.03679977, 131.0479936 ,  90.50606427,
       252.66486639,  84.84786067,  59.41005358, 184.51368208,
       201.46598714, 129.96333913,  90.65641478, 200.10932516,
        55.2884802 , 171.60459062, 195.40750666, 122.14139787,
       231.72783897, 159.49750022, 160.32104862, 165.53701866,
       260.73217736, 259.77213787, 204.69526082, 185.66480969,
        61.09821961, 209.9214333 , 108.50410841, 141.18

In [3]:
import keras

In [4]:
# cancer model marked as malignant or benign.
from sklearn.datasets import load_breast_cancer
cancer = load_breast_cancer()

x_train = cancer.data[:340]
y_train = cancer.target[:340]

x_test = cancer.data[340:]
y_test = cancer.target[340:]


In [5]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Dropout

In [6]:
model = Sequential()
model.add(Dense(15, input_dim=30, activation = 'relu'))
model.add(Dense(1,activation='sigmoid'))

In [7]:
model.compile(loss='binary_crossentropy', optimizer='rmsprop', metrics=['accuracy'])

In [9]:
model.fit(x_train, y_train, epochs=20,batch_size=50)

Epoch 1/20
340/340 [==============================] - 2s 5ms/step - loss: 8.6753 - acc: 0.4618
Epoch 2/20
340/340 [==============================] - 0s 62us/step - loss: 8.6753 - acc: 0.4618
Epoch 3/20
340/340 [==============================] - 0s 65us/step - loss: 8.6753 - acc: 0.4618
Epoch 4/20
340/340 [==============================] - 0s 59us/step - loss: 8.6753 - acc: 0.4618
Epoch 5/20
340/340 [==============================] - 0s 68us/step - loss: 8.6753 - acc: 0.4618
Epoch 6/20
340/340 [==============================] - 0s 76us/step - loss: 8.6753 - acc: 0.4618
Epoch 7/20
340/340 [==============================] - 0s 106us/step - loss: 8.6753 - acc: 0.4618
Epoch 8/20
340/340 [==============================] - 0s 76us/step - loss: 8.6753 - acc: 0.4618
Epoch 9/20
340/340 [==============================] - 0s 63us/step - loss: 8.6753 - acc: 0.4618
Epoch 10/20
340/340 [==============================] - 0s 75us/step - loss: 8.6753 - acc: 0.4618
Epoch 11/20
340/340 [==================

In [13]:
predictions = model.predict_classes(x_test)


In [15]:
from sklearn import metrics
print('Accuracy:', metrics.accuracy_score(y_true=y_test, y_pred=predictions))
print(metrics.classification_report(y_true=y_test, y_pred=predictions))

Accuracy: 0.24017467248908297
              precision    recall  f1-score   support

           0       0.24      1.00      0.39        55
           1       0.00      0.00      0.00       174

   micro avg       0.24      0.24      0.24       229
   macro avg       0.12      0.50      0.19       229
weighted avg       0.06      0.24      0.09       229



/home/grace/.local/lib/python3.5/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
